domainManagerIcon = "bx bxs-plane-take-off"
fileMangerIcon = "bx bxs-cart-download"
docsIcon = "bx bxs-collection"
layoutChangeIcon = "bx bxs-layout"
customizeLayoutIcon = "bx bxs-customize"
calenderIcon = 'bx bxs-calendar"
farLeftTopMenuIcon <i className="dripicons-align-justify" />
ChatIcon="dripicons-conversation"
exitFullScreenIcon="dripicons-backspace"
CryptoIcon="dripicons-jewel"
openSourceIcon="dripicons-network-2"
tasksIcon="dripicons-to-do"
dashboardIcon="dripicons-rocket"
cryptoWallet="dripicons-wallet"
financialIcon="dripicons-jewel"
propagationIcon="dripicons-clock"
invoiceIcon="dripicons-document"
projectsIcon="dripicons-archive"
webAdminIcon="dripicons-browser-upload"

email
nextEmailIcon="dripicons-skip"
returnBackIcon="dripicons-return"
replyAllIcon="dripicons-reply-all"
